# Generated by Django 3.2.8 on 2021-10-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_auto_20210916_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=60)),
                ('applied_intake_date', models.CharField(blank=True, max_length=60, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=60, null=True)),
                ('client_assignee', models.CharField(blank=True, max_length=60, null=True)),
                ('application_assignee', models.CharField(blank=True, max_length=60, null=True)),
                ('product', models.CharField(blank=True, max_length=60, null=True)),
                ('partner', models.CharField(blank=True, max_length=60, null=True)),
                ('partner_branches', models.CharField(blank=True, max_length=60, null=True)),
                ('partners_client_id', models.CharField(blank=True, max_length=60, null=True)),
                ('work_flow', models.CharField(blank=True, max_length=60, null=True)),
                ('application_start_by', models.CharField(blank=True, max_length=60, null=True)),
                ('application_start_by_branch', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('stage_in_queue', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='agents',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uni',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
