# Generated by Django 3.2.8 on 2021-10-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_auto_20211024_2153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agents',
            new_name='Agent',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
